### ISSUE TITLE
如果现在学习的话，选择Angular2还是React???

### ISSUE THREAD

**Issue by Jax0rz** [xufei/blog#32]

**Comment by afc163** [comment]
把别人的博客用来提问真的好么

**Comment by wwh447** [comment]
@Jax0rz 抛开具体业务和适用场合，单独谈论框架的好坏，和耍流氓有何分别？两个都要学，然后根据自己的业务情况选择合适的使用。如果是选择一个开始的话，我建议从 Angular2 开始。原因是从 A学到Z

**Comment by benjycui** [comment]
这个观点性的问题，还是去知乎问吧，然后 @ 几个老师就好

**Comment by dwqs** [comment]
这个跟你团队采用的技术栈也有关系吧  我们就是react路线的
