### ISSUE TITLE
xufei大神，冒昧的开个issue问个我很想知道的问题，谢谢~~~

### ISSUE THREAD

**Issue by yalishizhude** [xufei/blog#34]
使用Angular有一年时间了，今年开始使用node.js的时候，发现angular的指令和双向数据绑定和后端的数据模板技术有冲突。举个例子：
有一个可操作的表格，我想在node.js端用模板生成，但是这样的话浏览器端就脱离了$scope作用域，controller就不好操作了。所以现在涉及到用户交互的指令我都不得不额外发ajax请求，然后由$scope来填充模板，降低了性能。
所以我的问题是：**有没有办法由后端模板填充数据生成页面后，同时angular在浏览器端可以对其进行数据绑定？**

```
//后端模板填充
{{#list people}}
<tr>...</tr>
{{/list}}
```

```
//为了数据绑定，我只能通过angular在浏览器端这么写
<tr ng-repeat=" p in people">
...
</tr>
```

**Comment by afc163** [comment]
太冒昧了

**Comment by KingMario** [comment]
确实太冒昧了。
后端不要生成html，而是生成js数组到<script>标签里
另外，使用ajax取数据不是更方便吗？不要使用后端模板了。

**Comment by ourai** [comment]
你有考虑过别人的感受么

**Comment by flyfy1** [comment]
顺便想起昨天西乔这篇漫画：[一封邮件引发的血案](https://mp.weixin.qq.com/s?__biz=MzAxMzMxNDIyOA==&mid=2655543288&idx=1&sn=d990acb2b776258fa96c834f0bc36aaa&scene=1&srcid=0420kbTeevnp6gZHXoynZq3r&key=b28b03434249256ba24afca316d64952f3dcadff6c6d2192f7cd03b79782849422779a1e5ccf32e0ced1a612aed77b7a&ascene=0&uin=MjMyODI2OTA4MQ%3D%3D&devicetype=iMac+MacBookPro11%2C3+OSX+OSX+10.11.4+build(15E65)&version=11020201&pass_ticket=4pYpD%2BB3sNsNcnYVjWmouFbNmSmRzG7ksvltu3epVjnh8X0wsNOeu80d1J%2BLvwoE)

**Comment by yalishizhude** [comment]
@flyfy1 不好意思。。。

**Comment by yalishizhude** [comment]
@ourai 这应该就是用issue写博客的缺陷吧。。。

**Comment by yalishizhude** [comment]
@KingMario 感谢回答~~

>后端不要生成list相关的 html，而是生成js数组到script标签里，或者生成到ng-init指令里，鱼和熊掌就可得兼了

这样插一堆的script标签一方面不符合w3c的行为、样式、结构分离的规范，另一方面维护性也是很差的。

>使用ajax取数据未必会降低性能啊，你想后端是生成仅包含数据的数组快还是生成带标签、样式……的html代码快？并且把html部分写成静态之后，可以充分利用缓存、CDN……
即使前端渲染时有延迟等待现象，也可以通过一些技巧提升用户体验。

嗯，多了额外的ajax请求势必影响网络性能，同时还要对dom进行重绘，又加重了浏览器渲染负担。后端生成静态html就是为了性能考虑。

>另外，建议快停止使用后端模板吧，Angular这一类的把指令写在HTML标签里的MVVM框架出来之后，任何前、后端模板技术都会让你的代码显得难看、不好排版、不能充分利用编辑器的代码自动格式化功能，以及——最最重要的——难以查错。

感觉angular的指令就是一个前端模板，angular错误确实不太好查找。后端模板在不添加过多逻辑的情况下还是可以维护的，模板引擎编译的时候也会报错。排版的问题可以用插件解决的~

**Comment by KingMario** [comment]
> 这样插一堆的script标签一方面不符合w3c的行为、样式、结构分离的规范，另一方面维护性也是很差的。

看不出来会违反什么规范。再说还有ng-init啊。

关于性能方面，个人觉得比较“把占绝大部分的静态内容缓存”和“每次都全页刷新”，网络开销方面的性能优劣是不言而喻的，至于浏览器渲染的影响，由于上述网络开销方面的差异，可能与此正好相抵销。如果还存在差别，可以用一些“花招”来让用户在体验上感觉不明显。

> 感觉angular的指令就是一个前端模板，angular错误确实不太好查找。后端模板在不添加过多逻辑的情况下还是可以维护的，模板引擎编译的时候也会报错。排版的问题可以用插件解决的~   

你可以把加angular指令的html语句看作是模板，不过和其他使用花括号并且有“开门”、“关门”的模板相比，对于复杂的控制结构，这种“模板”犯错的机会大大减少了。

**Comment by benjycui** [comment]
@xufei 搞个 ama XD

**Comment by xufei** [comment]
……这什么鬼。

后端换一种不冲突的模板……

**Comment by hoosin** [comment]
叔叔
