### ISSUE TITLE
track问题

### ISSUE THREAD

**Issue by icy0225** [xufei/blog#40]
您好 我想问一下 这里里面为什么track by 的变量都是index呢 如果我里面的循环用的是$subindex就无法显示呢
<ul>
    <li ng-repeat="childArr in arr3 track by $index">
        {{$index}}
        <ul>
            <li ng-repeat="item in childArr track by $index">{{item}}</li>
        </ul>
    </li>
</ul>

**Comment by xufei** [comment]
这个是约定，$index表达的是当前循环的索引，不存在$subindex这个东西
